const properties = [
  {
    id: 0,
    name: "Marina Heights — Unit 4B",
    location: "Dubai Marina, UAE",
    region: "Dubai Marina",
    market: "dubai",
    category: "residential",
    type: "Residential",
    emoji: "🏙️",
    gradient: "linear-gradient(135deg, #1a9e72, #0f6e50)",
    badgeClass: "green",
    funded: 94,
    totalValue: 2100000,
    currency: "AED",
    minInvest: 500,
    annualReturn: 8.4,
    investors: 312,
    desc: "A fully furnished 2-bedroom apartment in the heart of Dubai Marina — one of the most sought-after residential locations in the UAE. Professionally managed with guaranteed maintenance and tenant vetting by DemoStake's in-house team.",
    facts: [
      ["Property type", "Apartment"],
      ["Size", "1,240 sqft"],
      ["Bedrooms / Bathrooms", "2 bed / 2 bath"],
      ["Year built", "2019"],
      ["Expected rental yield", "7.8% p.a."],
      ["Capital appreciation (projected)", "0.6% p.a."],
      ["Investment period", "5 years"],
      ["Exit window", "Bi-annual (June & December)"],
      ["Management fee", "15% of rental income"],
    ]
  },
  {
    id: 1,
    name: "King Abdullah Business Hub",
    location: "Riyadh, Saudi Arabia",
    region: "Riyadh CBD",
    market: "saudi",
    category: "commercial",
    type: "Commercial",
    emoji: "🏢",
    gradient: "linear-gradient(135deg, #185fa5, #0c447c)",
    badgeClass: "blue",
    funded: 62,
    totalValue: 5800000,
    currency: "SAR",
    minInvest: 500,
    annualReturn: 10.2,
    investors: 187,
    desc: "A premium commercial office space in Riyadh's booming financial district. Anchored by long-term corporate tenants, this property offers stable income and strong appreciation potential aligned with Vision 2030.",
    facts: [
      ["Property type", "Commercial office"],
      ["Size", "4,500 sqft"],
      ["Floor", "Levels 3–4"],
      ["Year built", "2021"],
      ["Expected rental yield", "9.5% p.a."],
      ["Capital appreciation (projected)", "0.7% p.a."],
      ["Investment period", "7 years"],
      ["Exit window", "Bi-annual (June & December)"],
      ["Management fee", "15% of rental income"],
    ]
  },
  {
    id: 2,
    name: "Burj Vista — Penthouse 12",
    location: "Downtown Dubai, UAE",
    region: "Downtown Dubai",
    market: "dubai",
    category: "luxury",
    type: "Luxury",
    emoji: "✨",
    gradient: "linear-gradient(135deg, #ba7517, #854f0b)",
    badgeClass: "amber",
    funded: 78,
    totalValue: 8500000,
    currency: "AED",
    minInvest: 500,
    annualReturn: 7.1,
    investors: 541,
    desc: "An ultra-luxury penthouse with panoramic views of Burj Khalifa and the Dubai Fountain. A trophy asset in the world's most iconic skyline, offering exceptional capital appreciation alongside premium short-term rental income.",
    facts: [
      ["Property type", "Luxury penthouse"],
      ["Size", "3,800 sqft"],
      ["Bedrooms / Bathrooms", "4 bed / 5 bath"],
      ["Year built", "2018"],
      ["Expected rental yield", "6.2% p.a."],
      ["Capital appreciation (projected)", "0.9% p.a."],
      ["Investment period", "5 years"],
      ["Exit window", "Bi-annual (June & December)"],
      ["Management fee", "15% of rental income"],
    ]
  },
  {
    id: 3,
    name: "Al Nakheel Residential Complex",
    location: "Jeddah, Saudi Arabia",
    region: "North Jeddah",
    market: "saudi",
    category: "residential",
    type: "Residential",
    emoji: "🌴",
    gradient: "linear-gradient(135deg, #3b6d11, #27500a)",
    badgeClass: "green",
    funded: 45,
    totalValue: 3200000,
    currency: "SAR",
    minInvest: 500,
    annualReturn: 9.3,
    investors: 94,
    desc: "A newly developed residential complex in Jeddah's fast-growing northern corridor. Designed for families with world-class amenities, close to schools and shopping centres. An ideal entry-point into the Saudi residential market.",
    facts: [
      ["Property type", "Residential complex"],
      ["Units", "12 apartments"],
      ["Average size", "950 sqft per unit"],
      ["Year built", "2023"],
      ["Expected rental yield", "8.7% p.a."],
      ["Capital appreciation (projected)", "0.6% p.a."],
      ["Investment period", "5 years"],
      ["Exit window", "Bi-annual (June & December)"],
      ["Management fee", "15% of rental income"],
    ]
  },
  {
    id: 4,
    name: "Business Bay Tower — Level 8",
    location: "Business Bay, Dubai",
    region: "Business Bay",
    market: "dubai",
    category: "commercial",
    type: "Commercial",
    emoji: "🏗️",
    gradient: "linear-gradient(135deg, #533ab7, #3c3489)",
    badgeClass: "blue",
    funded: 88,
    totalValue: 4600000,
    currency: "AED",
    minInvest: 500,
    annualReturn: 9.0,
    investors: 423,
    desc: "A modern grade-A commercial floor in the thriving Business Bay district, minutes from Downtown Dubai. Fully leased to a multinational tenant on a 3-year contract, providing stable and predictable rental income.",
    facts: [
      ["Property type", "Commercial office floor"],
      ["Size", "5,200 sqft"],
      ["Tenant", "Multinational corporation"],
      ["Year built", "2020"],
      ["Expected rental yield", "8.4% p.a."],
      ["Capital appreciation (projected)", "0.6% p.a."],
      ["Investment period", "5 years"],
      ["Exit window", "Bi-annual (June & December)"],
      ["Management fee", "15% of rental income"],
    ]
  },
  {
    id: 5,
    name: "Diriyah Heritage Villas",
    location: "Diriyah, Saudi Arabia",
    region: "Diriyah",
    market: "saudi",
    category: "luxury",
    type: "Luxury",
    emoji: "🕌",
    gradient: "linear-gradient(135deg, #993556, #72243e)",
    badgeClass: "pink",
    funded: 31,
    totalValue: 7100000,
    currency: "SAR",
    minInvest: 500,
    annualReturn: 11.5,
    investors: 58,
    desc: "A rare opportunity to invest in luxury villas near the UNESCO-listed Diriyah heritage site — one of the crown jewels of Vision 2030's tourism push. High growth potential as international visitor numbers surge year on year.",
    facts: [
      ["Property type", "Luxury villa complex"],
      ["Units", "4 villas"],
      ["Average size", "6,200 sqft per villa"],
      ["Year built", "2024"],
      ["Expected rental yield", "10.2% p.a."],
      ["Capital appreciation (projected)", "1.3% p.a."],
      ["Investment period", "7 years"],
      ["Exit window", "Bi-annual (June & December)"],
      ["Management fee", "15% of rental income"],
    ]
  }
];
